// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountFriendReceive: typeof import('./src/components/Account/AccountFriendRequest/src/components/AccountFriendReceive.vue')['default']
    AccountFriendReqItem: typeof import('./src/components/Account/AccountFriendRequest/src/components/AccountFriendReqItem.vue')['default']
    AccountFriendRequest: typeof import('./src/components/Account/AccountFriendRequest/AccountFriendRequest.vue')['default']
    AccountHome: typeof import('./src/components/Account/AccountHome.vue')['default']
    AllNews: typeof import('./src/components/News/AllNews/AllNews.vue')['default']
    ArticleItem: typeof import('./src/components/Detail/ArticleItem/ArticleItem.vue')['default']
    BigNews: typeof import('./src/components/News/LatestNews/BigNews.vue')['default']
    BubbleBox: typeof import('./src/components/Message/MessageBox/components/BubbleBox.vue')['default']
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    Comment: typeof import('./src/components/Detail/Comment/Comment.vue')['default']
    CommentItem: typeof import('./src/components/Detail/CommentItem/CommentItem.vue')['default']
    CustomEditor: typeof import('./src/components/Produce/CustomEditor/CustomEditor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    EquipmentItem: typeof import('./src/components/Player/EquipmentItem/EquipmentItem.vue')['default']
    FriendItem: typeof import('./src/components/Message/FriendItem/FriendItem.vue')['default']
    FriendSearch: typeof import('./src/components/Message/FriendSearch/FriendSearch.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HonorItem: typeof import('./src/components/Player/HonorItem/HonorItem.vue')['default']
    LatestNews: typeof import('./src/components/News/LatestNews/LatestNews.vue')['default']
    Login: typeof import('./src/components/Login/Login.vue')['default']
    MessageBox: typeof import('./src/components/Message/MessageBox/MessageBox.vue')['default']
    MessageEditor: typeof import('./src/components/Message/MessageEditor/MessageEditor.vue')['default']
    NewsItem: typeof import('./src/components/News/NewsItem/NewsItem.vue')['default']
    NotifyMessage: typeof import('./src/components/Header/NotifyMessage.vue')['default']
    OtherArticleItem: typeof import('./src/components/Detail/OtherArticleItem/OtherArticleItem.vue')['default']
    PlayerInfo: typeof import('./src/components/Player/PlayerInfo/PlayerInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarItem: typeof import('./src/components/Home/Stars/StarItem.vue')['default']
    Stars: typeof import('./src/components/Home/Stars/Stars.vue')['default']
    Tabs: typeof import('./src/components/News/Tabs/Tabs.vue')['default']
  }
}
